import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardSideBar from "@/components/DashboardSideBar"
import DashboardTopNav from "@/components/DashboardTopNav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Analytics Engine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
    <div className="grid min-h-screen w-full lg:grid-cols-[280px_1fr]">
      <DashboardSideBar />
      <DashboardTopNav >
        <main className="flex flex-col gap-4 p-4 lg:gap-6">
          {children}
        </main>
      </DashboardTopNav>
    </div>
    </body>
    </html>
  );
}
